# Generated by Django 3.2 on 2022-10-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221025_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(height_field=500, null=True, upload_to='D:\\Python\\News_Website\\media', width_field=800),
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(height_field=500, null=True, upload_to='D:\\Python\\News_Website\\media', width_field=800),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(height_field=500, null=True, upload_to='D:\\Python\\News_Website\\media', width_field=800),
        ),
    ]
