# Generated by Django 3.2 on 2022-10-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221025_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='main/img/news-800x500-3.jpg', upload_to='uploads/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(height_field=500, null=True, upload_to='MEDIA_ROOT', width_field=800),
        ),
    ]
