# Generated by Django 3.2 on 2022-10-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221025_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='released',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='views_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
