# Generated by Django 3.2 on 2022-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20221025_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='static/main/img/news-800x500-3.jpg', upload_to='uploads/post_images/'),
        ),
    ]
