# Generated by Django 3.2 on 2022-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='media/uploads/post_images/news-800x500-3.jpg', upload_to='uploads/post_images/'),
        ),
    ]
