# Generated by Django 3.2 on 2022-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='media/uploads/post_images/news-800x500-3.jpg', upload_to='media/uploads/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/post_images/'),
        ),
    ]
