# Generated by Django 3.2 on 2022-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20221025_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
