# Generated by Django 3.2 on 2022-10-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
