# Generated by Django 3.2 on 2022-10-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
