# Generated by Django 3.2 on 2022-10-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
