# Generated by Django 3.2 on 2022-10-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
    ]
